### ISSUE TITLE
[Bug]: spinner with ctrl+c dont working

### ISSUE THREAD

**Issue by productdevbook** [natemoo-re/clack#103]
**Environment**

- OS: [e.g. macOS, Windows]
- Node Version: v18.14.0
- Package: `@clack/prompts`, `@clack/core`
- Package Version: v0.6.3

**Describe the bug**
ctrl + c dont working with spinner. Whenever I add spinnir code, all ctrl commands are disabled.

dont working terminal ctrl + c kill.
```ts
import { execa, execaSync } from 'execa'

const s = p.spinner()
s.start('Emulator başlatılıyor')
s.stop('Emulator başlatıldı')
    
execaSync('pnpm', ['dev:app'], { stdio: 'inherit', detached: true })

```

working
```ts
import { execa, execaSync } from 'execa'

execaSync('pnpm', ['dev:app'], { stdio: 'inherit', detached: true })

```

**Comment by ulken** [comment]
Hum, I'm unable to reproduce. Using the basic example, `ctrl+c` exists the program (doesn't show an exit message, though, since the program abruptly exits). Not sure if by design or not. @natemoo-re?

What OS are you using?

**Comment by ulken** [comment]
https://user-images.githubusercontent.com/516549/223576891-9ba93558-cca4-4c7e-8767-4eda80269ee1.mov

**Comment by ulken** [comment]
This behavior seems to have been introduced in #80, as commenting out that line makes the program respond to control sequences again.

However, restoring raw mode as well seems to allow both fixes to co-exist.

`(input.isTTY) input.setRawMode(false);`

// cc @privatenumber
