### ISSUE TITLE
[Request] p.info

### ISSUE THREAD

**Issue by artegoser** [natemoo-re/clack#177]
**Is your feature request related to a problem? Please describe.**
It would be handy to have a function like this

**Describe the solution you'd like**
Is it possible to add a p.info function that will output the desired text in clack layout with line breaks, etc.

**Comment by ulken** [comment]
Sounds like you're looking for: [log](https://github.com/natemoo-re/clack/blob/90f8e3d762e96fde614fdf8da0529866649fafe2/packages/prompts/src/index.ts#L607)

**Comment by artegoser** [comment]
Yeah
