### ISSUE TITLE
[Bug] group

### ISSUE THREAD

**Issue by FedeRBeije** [natemoo-re/clack#188]
**Environment**

- OS: [macOS]
- Node Version: [v21.2.0]
- Package: [`@clack/prompts`]
- Package Version: [e.g. v0.7.0]

**Describe the bug**

1. When i try to use group from @clack/prompts i get undefined as results
2. If i just **_await group(..._** it print all in ones and i can't choose the values and does some strange glitch shows the outro but then it will removed it(video)
3. The var that should have the values from **_group_** is undefined. Also in the video
4. The onCancel method is not working. If i ctrl + c the program ends but not in the right way(video 2)

**To Reproduce**

Just create a group with select and multiselect

```js
const templateGroup = await group(
      {
        language: async () => {
          await select({
            message: 'Select a language',
            options: [
              {label: 'Typescript', value: 'typescript'},
              {label: 'Javascript', value: 'javascript'},
            ],
            initialValue: 'typescript',
          })
        },
        config: async () => {
          await multiselect({
            message: 'Select the config you want to use',
            options: [
              {value: 'tailwind', label: 'Tailwind'},
              {value: 'tanstackQuery', label: 'Tanstack Query', hint: 'recommended'},
              {value: 'zustand', label: 'Zustand', hint: 'recommended'},
              {value: 'redux', label: 'Redux'},
            ],
            initialValues: ['tailwind', 'tanstackQuery', 'zustand'],
            required: true,
          })
        },
      },
      {
        onCancel: () => {
          console.log('Operation cancelled')
          cancel('Operation cancelled')
          process.exit(0)
        },
      },
    )
 outro(`You selected ${templateGroup.language} and ${JSON.stringify(templateGroup.config)} for your project!`)
```

- Include reproduction steps

**Expected behavior**
I should get the values

**Additional Information**

![image](https://github.com/natemoo-re/clack/assets/108535310/8dcfd799-90e3-4d26-bf90-c37d4fba879d)

https://github.com/natemoo-re/clack/assets/108535310/9fd97ffc-bbba-4f20-82ea-9c4fa9d3a2d7

https://github.com/natemoo-re/clack/assets/108535310/f9f102d7-c34f-4b76-aef7-33cae1a477c7

**Comment by Mist3rBru** [comment]
Hello @FedeRBeije!

For the `group` to work, you need to return the prompt result at each call.

For example:
```diff
const templateGroup = await group(
      {
        language: async () => {
-         await select({
+         return await select({
            message: 'Select a language',
            options: [
              {label: 'Typescript', value: 'typescript'},
              {label: 'Javascript', value: 'javascript'},
            ],
            initialValue: 'typescript',
          })
        },
```

**Comment by FedeRBeije** [comment]
Okay, thanks. It my be better if you explicit that even thought sure was my mistaken not notice

**Comment by FedeRBeije** [comment]
Oh i see, my mistake sorry. Thanks

**Comment by Mist3rBru** [comment]
No problem! If you have any further questions or concerns, feel free to ask. 🚀
