### ISSUE TITLE
multiselect returns undefined

### ISSUE THREAD

**Issue by Mrahmani71** [natemoo-re/clack#21]
Hi, Is it a bug that "multiselect" return undefined in this [example](https://github.com/natemoo-re/clack/tree/main/examples/basic), Or did I do something wrong?

![Untitled](https://user-images.githubusercontent.com/13013819/218606454-adc55b89-3420-44de-8f62-6eb1249874df.gif)

**Comment by natemoo-re** [comment]
Fixed in [`@clack/core@0.1.2`](https://www.npmjs.com/package/@clack/core/v/0.1.2)
