### ISSUE TITLE
[Bug] validate method of text take the placeholder

### ISSUE THREAD

**Issue by LouisMazel** [natemoo-re/clack#29]
I tested the example in your README:

```ts
const meaning = await text({
  message: "What is the meaning of life?",
  placeholder: "Not sure",
  initialValue: "42",
  validate(value) {
    console.log('value', value)
    if (value.length === 0) return `Value is required!`;
  },
});
```

The value of the argument of validate method is the placeholder set in `text` method options (printed by the console.log)
So, you can't validate an empty response from the user

And by the way, the option `initialValue` is not available for this method and not working

**Comment by cacacaio** [comment]
Yeah I reached that problem aswell, my workaround was basically verifying if the value is equal to the placeholder for now and return false.

**Comment by natemoo-re** [comment]
Oops, yeah I didn't really think this one through. Placeholders don't work like this on the web, so this was an unintuitive choice.

Will fix!
