### ISSUE TITLE
[Feature Request] inquirer

### ISSUE THREAD

**Issue by Songkeys** [natemoo-re/clack#30]
Thank you for this project. Do you consider adding support for `inquirer`-like prompt?

**Comment by natemoo-re** [comment]
I'm familiar with the `inquirer` package, but I'm not too sure what `inquirer`-like prompt means in this context! Would you mind giving an example?

**Comment by Songkeys** [comment]
Sorry about the lack of information. It would be something like this:

<img width="486" alt="image" src="https://user-images.githubusercontent.com/22665058/219399950-61b5c702-8e6b-4b61-86fd-e6bc1daff9d9.png">

It's just multiple choices but with keyboard shortcuts instead of selecting with arrow keys. What do you think?

**Comment by natemoo-re** [comment]
Check out #59 and let me know if it's what you're thinking!

**Comment by Songkeys** [comment]
Thanks. I'll comment on that PR.

**Comment by natemoo-re** [comment]
Going to mark this as closed in #75!
