### ISSUE TITLE
Option for global onCancel

### ISSUE THREAD

**Issue by cacacaio** [natemoo-re/clack#37]
**Is your feature request related to a problem? Please describe.**
It's kinda frustating to have to put a isCancel after each prompt.

**Describe the solution you'd like**
Somewhere I can define a onCancel, that always like exits the process for example.

**Describe alternatives you've considered**
Have an onCancel prop on each prompt, so that if you Ctrl + C it auto executes the function on the prop

**Comment by natemoo-re** [comment]
Closed in https://github.com/natemoo-re/clack/pull/46, which will be released soon!

**Comment by natemoo-re** [comment]
Released in https://github.com/natemoo-re/clack/releases/tag/%40clack%2Fprompts%400.4.0
