### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by SeverinAlexB** [natemoo-re/clack#40]
**Environment**
 - OS: macOS
 - Node Version: v18.12.1
 - Package: `@clack/prompts`
 - Package Version: v0.2.2

**Describe the bug**
```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [ReadStream]. Use emitter.setMaxListeners() to increase limit
```
**To Reproduce**
After using the `await select` a lot, the warning message above shows up.

**Expected behavior**
Should not show up.

**Additional Information**
<img width="1138" alt="CleanShot 2023-02-15 at 10 12 03@2x" src="https://user-images.githubusercontent.com/8782386/218970015-4eb676a6-49dd-49e8-9efd-28ac642b9ac4.png">

Let me know if you got questions. It's probably just even emitter listener cleanup.

**Comment by wrodriguez83** [comment]
It happens to me too, but after 10 differents prompts (confirms, select, inputs, etc)

**Comment by ulken** [comment]
I looked into this and think I found the culprit (at least the warning no longer shows up after generating 10+ prompts).

**Comment by kyllan16693** [comment]
I still have this issue. Is the best work around setting max emitters to 0?
