### ISSUE TITLE
[Request] Hide last prompt to show new one

### ISSUE THREAD

**Issue by HypnoticSiege** [natemoo-re/clack#43]
Let's say you have 5 prompts for installing a database. These prompts ask for things like host, port, user, password, etc.
I'd love for clack to be able to hide/remove the last prompt and cleanly display the next prompt. I think that this would allow the console to be cleaner and just show the user what they are currently interacting with/answering.

**Comment by natemoo-re** [comment]
Could you not do `console.clear()` after each question is answered?

**Comment by HypnoticSiege** [comment]
> Could you not do `console.clear()` after each question is answered?

That's very true. Honestly didn't even think of that at the moment 😅
Thanks a lot Nate! :)
