### ISSUE TITLE
[Request] Support neovim horizontal/vertical motions

### ISSUE THREAD

**Issue by esau-morais** [natemoo-re/clack#45]
**Is your feature request related to a problem? Please describe.**
When trying to use hjkl (motion) to go through the options, nothing happens.

**Describe the solution you'd like**
Get to move through options using hjkl.

**Additional context**
e.g.: When I create a new React Native app, it gives me options to select and I'm able to use hjkl to move through them.

Environment: Tmux

**Comment by natemoo-re** [comment]
This seems reasonable, I'd definitely review a PR for this!

Should be a pretty straight-forward change to map `h | j | k | l` to the correct direction, then emit a `cursor` event here.
https://github.com/natemoo-re/clack/blob/main/packages/core/src/prompts/prompt.ts#L148-L150

**Comment by esau-morais** [comment]
I'll open a PR solving this issue ASAP, thank you for the clue
