### ISSUE TITLE
[Request] Multiselect allows empty

### ISSUE THREAD

**Issue by zihan-ch** [natemoo-re/clack#52]
It seems that multiselect requires at least one selected option. I hope there could be an option to determine if the multiselect allows zero chosen options.

**Comment by natemoo-re** [comment]
Closed in https://github.com/natemoo-re/clack/pull/42, going out soon!

**Comment by natemoo-re** [comment]
Released in https://github.com/natemoo-re/clack/releases/tag/%40clack%2Fprompts%400.4.0
