### ISSUE TITLE
[Feature Request] Need  a `onCancel` property

### ISSUE THREAD

**Issue by AkaraChen** [natemoo-re/clack#54]
**Is your feature request related to a problem? Please describe.**

I think have a `onCancel` property will be better.

Currently I need to call `isCanceled` in every prompts, I think it is troublesome.

**Describe the solution you'd like**

```ts
import { text, cancel } from '@clack/prompts'

const result = await text({
	/* Other options */
	onCancel() {
		cancel('Operation canceled.')
		process.exit(1)
	}
})
```

**Comment by cpreston321** [comment]
Hey @AkaraChen until there is a definite solution within core then we can add these options per prompt. I'm the meantime you can wrap within a the group function and within the second param you pass onCancel like you have above. 

Example here: https://github.com/natemoo-re/clack/blob/main/examples/basic/index.ts

**Comment by AkaraChen** [comment]
Thanks for such a quick reply.
