### ISSUE TITLE
[Request] Pre-define a multiselect answer as selected

### ISSUE THREAD

**Issue by banjo** [natemoo-re/clack#62]
**Is your feature request related to a problem? Please describe.**
Having a multi-select with some answers pre-defined

**Describe the solution you'd like**
Being able to pre-define a multi-select with `selected: true` or something similar. 

**Describe alternatives you've considered**
Using another library, unfortunately.

**Additional context**
Love this library, and thing it works great :)

**Comment by ulken** [comment]
This is already supported, although the docs are lacking. The options you have at your disposal are:

```ts
	message: string;
	options: Options;
	initialValue?: Options[number]['value'][];
	required?: boolean;
	cursorAt?: Options[number]['value'];
```

You're looking for `initialValue` and potentially `cursorAt`.

**Comment by banjo** [comment]
Amazing, thanks. However, a neat enhancement would in that case be to include it with a `selected` flag in the options.

**Comment by ulken** [comment]
@natemoo-re on a related note: should `initialValue` be pluralized for this component to more clearly indicate it represents a list?

**Comment by ulken** [comment]
> However, a neat enhancement would in that case be to include it with a selected flag in the options.

Yeah, that's another way to do it (as in HTML), but adding support for both will most likely not happen as it would make both the API and implementation unnecessarily complex.

I think the current API better conveys the fact that it's just the initial value(s). It aligns better with other components as well. 

Besides, in contrast to the DOM, the `selected` attribute wouldn't be updated (as in moved to another option) when the selection changes.

**Comment by ulken** [comment]
@banjo I'm gonna go ahead and close this issue. Hope you feel I've addressed your concern.

@natemoo-re the question aimed towards you is still relevant.

**Comment by natemoo-re** [comment]
> @banjo I'm gonna go ahead and close this issue. Hope you feel I've addressed your concern.
> 
> @natemoo-re the question aimed towards you is still relevant.

@ulken agreed that `initialValue` should probably be `initialValues` here.

**Comment by ulken** [comment]
> @ulken agreed that `initialValue` should probably be `initialValues` here.

#73
