### ISSUE TITLE
[Bug] Multi-Select returns options rather than values

### ISSUE THREAD

**Issue by coSevenSeven** [natemoo-re/clack#67]
**Environment**

- OS: Windows
- Node Version: v16.18.0
- Package: @clack/prompts
- Package Version: ^0.4.4

**Describe the bug**
As [README](https://github.com/natemoo-re/clack/tree/main/packages/prompts#multi-select) mentions, multi-select returns an array with all selected `value` props, but it returns options selected.

**To Reproduce**

https://user-images.githubusercontent.com/108878201/220267650-d41df77b-84ed-4705-a4cb-26da1a966fa6.mp4

**Expected behavior**
multi-select should return array with values selected.

**Comment by ulken** [comment]
Yes, that's on me. The previous implementation had its types wrong, which seem to have confused me while refactoring this.

I'll get it fixed.
