### ISSUE TITLE
[Bug] Win/MinGW - spinner() breaks confirm()/select(), but only for the second one

### ISSUE THREAD

**Issue by wadabum** [natemoo-re/clack#76]
**Environment**

- OS: **mingw64** via `git 2.39.1.windows.1`
- Node Version: `v16`
- Package: `@clack/prompts`
- Package Version: `v0.4.4`

**Describe the bug**
The second (and only that) `confirm()`/`select()` after a `spinner()` breaks.
-> no reaction to left/right/up/down keys
pressing enter feeds a break, but still shows no text
left/right/up/down key then redraws the yes/no a line below (notable breaking the colored `L` too)

**To Reproduce**
https://stackblitz.com/edit/node-bnwkvt?file=index.ts
**not reproduceable on stackblitz** -> this seems to be a windows-terminal issue maybe?...

- Install windows, Node, git https://git-scm.com/download/win
- "open gitbash" inside the downloaded stackblitz from above
- `npm i && npm run script`
- observe Q1 works
- observe Q2 works
- watch the spinner
- observe Q3 works
- notice that Q4 seems to not do anything
- press enter, arrowkeys, 
- *now* you can select Q4
- observe Q5 working wonderfully again

**Expected behavior**
Q4 should not print twice, and not need three keypresses (enter to void, arrow to render, enter to select)

**Additional Information**
![](https://i.imgur.com/cEW45Ho.gif)

**Comment by ulken** [comment]
Interesting. I wonder if something's not cleaned up correctly.

I don't have access to a Windows env, but I'll see if I can reproduce elsewhere or reason my way around potential issues.

Are the reproduction steps as minimal as possible?

**Comment by wadabum** [comment]
> minimal as possible?  

Replace examples/basic/index.ts with this:
```TypeScript
import * as p from '@clack/prompts';
import { setTimeout } from 'node:timers/promises';
 
async function main() {
    console.clear();
 
    const confirmed1 = await p.confirm({
        message: `Here you can select\n\n   1\n`,
    });
    
    const confirmed2 = await p.confirm({
        message: `Here you can also select\n\n   2\n`,
    });
    
    const detecting = p.spinner();
    detecting.start();
    await setTimeout(2000);
    detecting.stop();
 
    const confirmed3 = await p.confirm({
        message: `FIRST after the spinner is OK\n\n   3\n`,
    });
    
    const confirmed4 = await p.confirm({
        message: `THIS is broken, needs one extra [enter] press, and then an [arrow-key]\n\n   4\n`,
    });
    
    const confirmed5 = await p.confirm({
        message: `and now this is ok again.\n\n   5\n`,
    });
 
}
 
main().catch(console.error);
```

Q1, Q2 and Q5 are purely for demonstration,
spinner & Q3 cause it, Q4 is the trouble

Ive cloned this repo and have poked around in it quite a bit with force lock/unlocking and things there like i found 
all to no effect.

**Comment by ulken** [comment]
Unable to reproduce, but I did find one bug in `block()`. No idea if it solves your problem or not. Could you try checking out the `fix-block` branch and see if it makes any difference?

**Comment by wadabum** [comment]
Hm... yes-and-no...
It does NOT fix it, but "its very close":

Going from that diff ive poked a bit more...
- `fix-block` makes no difference at all, the `rl.close();` in the return does already take care of it
```
// branch: main
{ where: 'block()->return()-early', isTTY: true, isRaw: true }
{ where: 'block()->return()-post-off', isTTY: true, isRaw: true }
{ where: 'block()->return()-post-hide', isTTY: true, isRaw: true }
{ where: 'block()->return()-post-close', isTTY: true, isRaw: false }
{ where: 'main()->after-spinner/before-3', isTTY: true, isRaw: false }
```
- combined with this, 
 the early `if (input.isTTY) input.setRawMode(true);` does not rly do anything,
 `const rl = readline.createInterface...` does already switch isRaw from false to true (at least for me here ;D)
```
{ where: 'main()->before-spinner', isTTY: true, isRaw: false }
{ where: 'block()-early', isTTY: true, isRaw: false }
{ where: 'block()-post-rl', isTTY: true, isRaw: true }
{ where: 'block()-post-rl-emit', isTTY: true, isRaw: true }
{ where: 'block()-post-set', isTTY: true, isRaw: true }
```

#### And I actually managed to "fix" it...
-> by DIRECTLY resetting raw mode, and not "waiting until the return()"
so *inverting* the existing line 20 to `input.setRawMode(false);`  
Effectively resetting what `readline.createInterface` did 2 lines above before it "prints any output and waits"?
- and it still spins, 
- prints animated dots, 
- and ignores all but Ctrl+C as expected...

Sounds a bit spooky to me, but given that original code is only 2 weeks old it could be a thing i guess :D
Maybe @natemoo-re got smth to say? your commit 😋

```diff
diff --git a/packages/core/src/utils.ts b/packages/core/src/utils.ts
@@ -17,7 +17,7 @@ export function block({
                tabSize: 1,
        });
        readline.emitKeypressEvents(input, rl);
-       if (input.isTTY) input.setRawMode(true);
+       if (input.isTTY) input.setRawMode(false);

        const clear = (data: Buffer, { name }: Key) => {
                const str = String(data);
```
```
{ where: 'main()->before-spinner', isTTY: true, isRaw: false }
{ where: 'block()-early', isTTY: true, isRaw: false }
{ where: 'block()-post-rl', isTTY: true, isRaw: true }
{ where: 'block()-post-rl-emit', isTTY: true, isRaw: true }
{ where: 'block()-post-set', isTTY: true, isRaw: false }
```
![](https://i.imgur.com/eSYwBJt.gif)

**Comment by privatenumber** [comment]
I think we're encountering this in aicommits too:
https://github.com/Nutlope/aicommits/pull/102

I went through the clack code and narrowed it down to this reproduction and fix:
https://github.com/nodejs/node/issues/31762#issuecomment-1441223907

To apply it to this project, adding `rl.terminal=false;` above this line should fix it:
https://github.com/natemoo-re/clack/blob/cc11917a3227c7fee2a755c0be498421a28c15f6/packages/core/src/utils.ts#L43

@wadabum 
Would you mind seeing if the reproduction & fix works for you?

@ulken 
I'm using a Mac with Virtual Box running Windows 11. It's a free setup if you want to try to reproduce ([guide](https://www.makeuseof.com/virtualbox-70-install-windows-11/).

**Comment by ulken** [comment]
Glad we got things rolling. Nice digging folks!

> * `fix-block` makes no difference at all, the `rl.close();` in the return does already take care of it

You're right. Then we should be able to remove all usages of [setRawMode()](https://github.com/natemoo-re/clack/blob/main/packages/core/src/prompts/prompt.ts#L28) in core as well?

For reference, I'm including some docs on the behavior of `terminal`.

From **readline.createInterface()**

> `terminal` <boolean> true if the input and output streams should be treated like a TTY, and have ANSI/VT100 escape codes written to it. Default: checking isTTY on the output stream upon instantiation.

From **readline.emitKeypressEvents()**

> If the stream is a TTY, then it must be in raw mode.
>
> This is automatically called by any readline instance on its input if the input is a terminal. Closing the readline instance does not stop the input from emitting 'keypress' events.
>
> ```ts
> readline.emitKeypressEvents(process.stdin);
> if (process.stdin.isTTY)
>  process.stdin.setRawMode(true);
> ```

> @ulken
> I'm using a Mac with Virtual Box running Windows 11. It's a free setup if you want to try to reproduce ([guide](https://www.makeuseof.com/virtualbox-70-install-windows-11/)).

Thanks!

**Comment by wadabum** [comment]
Just to follow up - can confirm that current main branch is all working as expected now.
Thanks everyone!

**Comment by Benjamin-Frost** [comment]
@natemoo-re, I'm encountering this exact issue on `v0.7.0`. I used the same code mentioned above to reproduce. It breaks on Windows and works correctly on macOS. Could you please verify if you can replicate this issue as well?

<details>
  <summary>Code for reproduction</summary>

  ```ts
import * as p from '@clack/prompts';
import { setTimeout } from 'node:timers/promises';
 
async function main() {
    console.clear();
 
    const confirmed1 = await p.confirm({
        message: `Here you can select\n\n   1\n`,
    });
    
    const confirmed2 = await p.confirm({
        message: `Here you can also select\n\n   2\n`,
    });
    
    const detecting = p.spinner();
    detecting.start();
    await setTimeout(2000);
    detecting.stop();
 
    const confirmed3 = await p.confirm({
        message: `FIRST after the spinner is OK\n\n   3\n`,
    });
    
    const confirmed4 = await p.confirm({
        message: `THIS is broken, needs one extra [enter] press, and then an [arrow-key]\n\n   4\n`,
    });
    
    const confirmed5 = await p.confirm({
        message: `and now this is ok again.\n\n   5\n`,
    });
 
}
 
main().catch(console.error);
  ```
</details>
